name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Bump Version Patch
      run: |
        # Extract the current version without the -SNAPSHOT suffix from pom.xml
        CURRENT_VERSION=$(grep "<version>.*-SNAPSHOT</version>" pom.xml | head -1 | awk -F'[-><]' '{print $3}')
        echo "Current Version: $CURRENT_VERSION"

        # Increment the patch version
        IFS='.' read -r -a parts <<< "$CURRENT_VERSION"
        new_patch=$((parts[2] + 1))
        NEW_VERSION="${parts[0]}.${parts[1]}.$new_patch"
        echo "New Version: $NEW_VERSION"

        # Update pom.xml with the new version
        sed -i "s/<version>$CURRENT_VERSION-SNAPSHOT<\/version>/<version>$NEW_VERSION-SNAPSHOT<\/version>/" pom.xml

    - name: Build Docker Image
      run: |
        docker build -t my-java-app:latest .

    - name: Push Docker Image
      run: |
        docker tag my-java-app:latest danos23/java-ci-cd:latest
        docker push danos23/java-ci-cd:latest

