name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Automated Version Bump
      uses: "pascalgn/automated-version-bump@v2"
      with:
        github_token: ${{ secrets.GH_PAT }}
        commit_message: "Bump version"

    - name: Build Docker Image
      run: |
        docker build -t my-java-app:latest .

    - name: Push Docker Image
      run: |
        docker tag my-java-app:latest danos23/java-ci-cd:latest
        docker push danos23/java-ci-cd:latest

